### PR TITLE
Raul request: allow raul access

### PR DESCRIPTION
**Pull request by KevinMcHugh**
i wrote this code in github so i have not tested it

### CODE REVIEW

**Comment by mkuipers** [comment]
please see the community guidelines for how to submit a PR properly for this repo:

https://github.com/mkuipers/rauls/blob/master/README.md#contributing

**Comment by mkuipers** [comment]
closing because it wasn't a proper pr

**Comment by KevinMcHugh** [comment]
Wtf

**Comment by mkuipers** [comment]
please follow the guidelines and resubmit

**Comment by mkuipers** [comment]
look, you have to understand, we get a lot of PRs for this project and it's important to write them the right way otherwise they'll never see the light of day

**Comment by KevinMcHugh** [comment]
No

**Comment by mkuipers** [comment]
ok

**Comment by KevinMcHugh** [comment]
Thanks

**Pull request merged**
